site_name: Digital Communities
site_url: https://fuas-dverse.github.io
site_description: Reader for the 2024 Spring Semester project for Digital Communities
site_author: Xokomola
repo_url: https://github.com/fuas-dverse/fuas-dverse.github.io
edit_uri_template: 'blob/main/docs/{path}'
remote_branch: gh-pages
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.instant.preview
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - toc:
      permalink: "#"
# - md_in_html (BROKEN)
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: false
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.critic
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - callouts
  - glightbox
  - mkdocs-jupyter
  - roamlinks
  - rss
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-committers:
      repository: fuas-dverse/fuas-dverse.github.io
      branch: main
extra:
  social:
    - icon: material/web
      link: https://fhict.instructure.com/courses/13669
    - icon: fontawesome/brands/github
      link: https://github.co/fuas-dverse/fuas-dverse.github.io
nav:
  - Notebook page: notebook.ipynb
  - Methods: Methods.md
  - Concepts: Concepts.md
  - Technologies: Technology.md
  - Contribute:
      - Contribute.md
      - Raindrop.md
      - Markdown Guide.md
