site_name: Digital Communities
site_url: https://fuas-dverse.github.io
site_description: Building a decentralized social network platform for human and non-human agents.
site_author: Xokomola
repo_url: https://github.com/fuas-dverse/fuas-dverse.github.io
edit_uri_template: 'blob/main/docs/{path}'
copyright: © 2024. Licensed via CC BY-NC-SA 4.0
remote_branch: gh-pages
use_directory_urls: false
theme:
  name: material
  custom_dir: custom_theme/
  palette:
    primary: deep purple
  features:
    - toc.follow
    - toc.integrate
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    #- navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - tables
  - toc:
      permalink: "#"
# Following items break the build
# - md_in_html
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: vega-lite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: false
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.critic
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5 
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - javascripts/mathjax.js
  - javascripts/mermaid.js
plugins:
  - search
  - tags:
      tags_file: tags.md
  - callouts
  - glightbox
  - mkdocs-jupyter
  - roamlinks
  - rss:
      categories:
        - categories
        - tags
  - git-revision-date-localized:
      fallback_to_build_date: true
  - git-committers:
      repository: fuas-dverse/fuas-dverse.github.io
      branch: main
      exclude:
        - About.md
        - README.md
        - References.md
        - index.md
        - News.md
        - projects/index.md
        - concepts/index.md
        - articles/index.md
        - contribute/**
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fuas-dverse/fuas-dverse.github.io
nav:
  - About: About.md
  - Projects: projects/index.md
  - Concepts: concepts/index.md
  - Articles: articles/index.md
  - References: References.md
  - Contribute:
      - contribute/index.md
      - contribute/Raindrop.md
      - contribute/Markdown Guide.md
      - contribute/Obsidian.md
